spring.application.name=profile-service
server.port=8006

order.service.url=${ORDER_SERVICE_URL:http://localhost:8002}

spring.datasource.url=${PROFILE_DATABASE_URL:jdbc:h2:mem:profiles;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
spring.datasource.username=${PROFILE_DATABASE_USERNAME:sa}
spring.datasource.password=${PROFILE_DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
