export const stitchColors = {
  "tertiary-fixed-dim": "#ecc068",
  "surface-container-high": "#e7e8e8",
  background: "#f8faf9",
  "inverse-surface": "#2e3131",
  "surface-bright": "#f8faf9",
  "primary-container": "#659d9e",
  "dark-text": "#242426",
  "surface-container-lowest": "#ffffff",
  "on-surface-variant": "#404848",
  "tertiary-fixed": "#ffdea2",
  "primary-light": "#96C7C8",
  "surface-light": "#FFE7C3",
  "on-primary": "#ffffff",
  "on-primary-fixed-variant": "#0e4f50",
  "primary-fixed-dim": "#98d1d1",
  "surface-tint": "#2d6768",
  "on-primary-container": "#003233",
  "on-secondary": "#ffffff",
  "primary-fixed": "#b3edee",
  "on-tertiary-fixed": "#261900",
  "on-surface": "#191c1c",
  error: "#ba1a1a",
  "on-secondary-container": "#476966",
  "on-error": "#ffffff",
  surface: "#F0E9E2",
  "surface-container": "#edeeed",
  secondary: "#436462",
  "inverse-primary": "#98d1d1",
  "surface-variant": "#e1e3e2",
  tertiary: "#795905",
  "secondary-container": "#c3e7e4",
  "secondary-fixed": "#c6eae7",
  "on-secondary-fixed": "#00201f",
  "secondary-fixed-dim": "#aacdcb",
  "on-background": "#191c1c",
  "surface-container-low": "#f2f4f3",
  "on-primary-fixed": "#002020",
  "on-tertiary-fixed-variant": "#5c4200",
  primary: "#2d6768",
  "error-container": "#ffdad6",
  "surface-container-highest": "#e1e3e2",
  "surface-dim": "#d9dada",
  "on-tertiary-container": "#3b2900",
  outline: "#707979",
  "inverse-on-surface": "#f0f1f0",
  "on-tertiary": "#ffffff",
  "on-secondary-fixed-variant": "#2b4c4a",
  "outline-variant": "#bfc8c8",
  "tertiary-container": "#b48e3b",
  "on-error-container": "#93000a",
};

export const stitchBorderRadius = {
  DEFAULT: "0.25rem",
  lg: "0.5rem",
  xl: "0.75rem",
  full: "9999px",
};

export const stitchSpacing = {
  "container-max": "1200px",
  "stack-lg": "32px",
  "margin-x": "32px",
  gutter: "24px",
  "stack-sm": "8px",
  "stack-md": "16px",
};

export const stitchFontFamily = {
  sans: ["Rethink Sans", "sans-serif"],
  "card-title": ["Rethink Sans", "sans-serif"],
  metadata: ["Rethink Sans", "sans-serif"],
  "page-title": ["Rethink Sans", "sans-serif"],
  "section-title": ["Rethink Sans", "sans-serif"],
  "display-hero": ["Rethink Sans", "sans-serif"],
  "body-md": ["Rethink Sans", "sans-serif"],
  button: ["Rethink Sans", "sans-serif"],
};

export const stitchFontSize = {
  "card-title": ["20px", { lineHeight: "1.4", fontWeight: "650" }],
  metadata: ["14px", { lineHeight: "1.4", fontWeight: "500" }],
  "page-title": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
  "section-title": ["28px", { lineHeight: "1.3", fontWeight: "650" }],
  "display-hero": ["56px", { lineHeight: "1.2", fontWeight: "700" }],
  "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
  button: ["16px", { lineHeight: "1", fontWeight: "650" }],
};

export const stitchBoxShadow = {
  stitch: "0 12px 32px rgba(36, 36, 38, 0.08)",
  subtle: "0 12px 32px rgba(36, 36, 38, 0.04)",
};
