server.port=8005

restaurant-service.base-url=http://localhost:8001/api
# ${DEEPL_API_KEY}
deepl.api-key=4d5630f6-1b57-4929-8090-68699547b001:fx  
deepl.base-url=https://api-free.deepl.com/v2/translate
logging.level.org.springframework.cache=DEBUG
cache.caffeine.spec=maximumSize=500,expireAfterAccess=10m